'use client';

import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from '@/components/ui/dialog';
import { LoaderCircle, Plus } from 'lucide-react';
import React, { Dispatch, SetStateAction, useState } from 'react';

import { zodResolver } from '@hookform/resolvers/zod';
import { useForm, UseFormReturn } from 'react-hook-form';
import { z } from 'zod';

import { Loader5 } from '@/components/loader';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import {
	Form,
	FormControl,
	FormField,
	FormItem,
	FormLabel,
	FormMessage,
} from '@/components/ui/form';
import { Textarea } from '@/components/ui/textarea';
import { alertConfirm, handleValidationError } from '@/lib';
import { toast } from 'sonner';
import { useDevCategoryQuery } from '../dev-category';
import { IDevSubCategory, IDevSubCategoryStatus } from '../dev-sub-category';
import { useRoleStoreMutation } from './api-slice';
import { IRoleStatus } from './type';

// --- Zod Schema ---
const schema = z.object({
	name: z
		.string({ error: 'Name is required' })
		.trim()
		.min(1, 'Name is required'),
	roleKey: z
		.string({ error: 'Role Key is required' })
		.trim()
		.min(1, 'Role Key is required'),
	description: z.string().trim().optional(),
	status: z.enum([
		IRoleStatus.Active,
		IRoleStatus.Inactive,
		IRoleStatus.Trashed,
	]),
	permissionIds: z.array(z.string()).min(1, 'Select at least one permission'),
});

type ZodType = z.infer<typeof schema>;

export function RoleStore() {
	const [open, setOpen] = useState(false);

	return (
		<Dialog open={open} onOpenChange={setOpen}>
			<DialogTrigger asChild>
				<Button size="lg" variant="brand">
					<Plus className="h-4 w-4" />
					<span className="hidden lg:inline">Create Role</span>
				</Button>
			</DialogTrigger>

			<DialogContent className="sm:max-w-[1200px] overflow-y-scroll max-h-[90vh] ">
				<DialogHeader>
					<DialogTitle>Create Role</DialogTitle>
					<DialogDescription>Create a new role.</DialogDescription>
				</DialogHeader>

				<FORM setOpen={setOpen} />
			</DialogContent>
		</Dialog>
	);
}

const FORM = ({ setOpen }: { setOpen: Dispatch<SetStateAction<boolean>> }) => {
	const [store, { isLoading }] = useRoleStoreMutation();
	const { data: permissions, isLoading: isLoadingPermissions } =
		useDevCategoryQuery({
			status: 'active',
			page: 1,
			limit: 'all',
		});

	const form = useForm<ZodType>({
		resolver: zodResolver(schema),
		defaultValues: {
			description: '',
			name: '',
			roleKey: '',
			status: IRoleStatus.Active,
			permissionIds: [],
		},
	});

	// Watch the name field and auto-update role key
	const watchedName = form.watch('name');

	// Auto-generate role key when name changes
	React.useEffect(() => {
		if (watchedName) {
			const autoGeneratedRoleKey = watchedName
				.toLowerCase()
				.replace(/\s+/g, '_')
				.trim();
			form.setValue('roleKey', autoGeneratedRoleKey);
		}
	}, [watchedName, form]);

	const onSubmit = async (data: ZodType) => {
		alertConfirm({
			onOk: async () => {
				try {
					const response = await store(data).unwrap();
					if (response.status) {
						toast.success(response.message || 'Updated successfully');
						form.reset();
						setOpen(false);
					} else {
						if (!response?.status) {
							handleValidationError(response, form.setError);
						} else {
							toast.error(response.message || 'Something went wrong');
						}
					}
				} catch (error: any) {
					if (error?.status === 400) {
						handleValidationError(error, form.setError);
					} else {
						toast.error('Something went wrong');
					}
				}
			},
		});
	};

	if (isLoadingPermissions) {
		return (
			<>
				<Loader5 />
				<Loader5 />
			</>
		);
	}

	return (
		<Form {...form}>
			<form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
				<div className="grid grid-cols-1 md:grid-cols-2 gap-4">
					{/* Name */}
					<FormField
						control={form.control}
						name="name"
						render={({ field }) => (
							<FormItem>
								<FormLabel>Name</FormLabel>
								<FormControl>
									<Textarea {...field} placeholder="Type role name..." />
								</FormControl>
								<FormMessage />
							</FormItem>
						)}
					/>

					{/* Description */}
					<FormField
						control={form.control}
						name="description"
						render={({ field }) => (
							<FormItem>
								<FormLabel>Description</FormLabel>
								<FormControl>
									<Textarea {...field} placeholder="Type description..." />
								</FormControl>
								<FormMessage />
							</FormItem>
						)}
					/>
				</div>

				<FormField
					control={form.control}
					name="permissionIds"
					render={() => (
						<FormItem>
							<FormLabel>Permissions</FormLabel>
							<div className="grid grid-cols-1 md:grid-cols-3 gap-4">
								{permissions?.data.map((permission) => {
									if (permission.subCategories.length <= 0) {
										return false;
									}
									return (
										<div key={permission.id} className="border p-3 rounded-md">
											<h3 className="font-medium mb-2">{permission.name}</h3>
											<div className="space-y-2">
												{subCategoryCheckboxes(permission.subCategories, form)}
											</div>
										</div>
									);
								})}
							</div>
							<FormMessage />
						</FormItem>
					)}
				/>

				<DialogFooter>
					<Button type="submit" disabled={isLoading}>
						{isLoading && (
							<LoaderCircle className="mr-2 h-4 w-4 animate-spin" />
						)}
						{isLoading ? 'Creating...' : 'Create Role'}
					</Button>
				</DialogFooter>
			</form>
		</Form>
	);
};

export const subCategoryCheckboxes = (
	subCategories: IDevSubCategory[],
	form: UseFormReturn<ZodType>
) => {
	const values = form.watch('permissionIds') as string[];

	const filteredSubCategories = subCategories.filter(
		(subCategory) =>
			subCategory.status !== IDevSubCategoryStatus.Trashed &&
			subCategory.status !== IDevSubCategoryStatus.Inactive
	);

	return filteredSubCategories.map((subCategory) => (
		<FormField
			key={subCategory.id}
			control={form.control}
			name="permissionIds"
			render={({ field }) => {
				const isChecked = values?.includes(subCategory.id.toString());

				const toggleCheckbox = (checked: boolean) => {
					const newValue = checked
						? [...(values || []), subCategory.id.toString()]
						: values?.filter((id) => id !== subCategory.id.toString());

					field.onChange(newValue);
				};

				return (
					<FormItem
						key={subCategory.id}
						className="flex items-center space-x-2"
					>
						<FormControl>
							<Checkbox
								checked={isChecked}
								onCheckedChange={toggleCheckbox}
								id={`permission-${subCategory.id}`}
							/>
						</FormControl>
						<FormLabel htmlFor={`permission-${subCategory.id}`}>
							{subCategory.name}
						</FormLabel>
					</FormItem>
				);
			}}
		/>
	));
};
